[package]
name = "script-utils"
version = "0.1.0"
edition = "2018"

[dependencies]
ckb-std = "0.7.1"
sparse-merkle-tree = {version = "0.4.0-rc1", default_features = false}
cfg-if = "0.1"
blake2b-ref = "0.1"

